---
title: "Figure 1"
author: "Guillaume Kugener"
date: "5/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gridExtra)
library(grid)
library(MASS)
source('~/Documents/USC/USC_docs/ml/surgical-training-project/analysis/carotid_model/preprocess_data.R')
```

```{r}
scatter_ebl_tth <- raw_data %>% 
  dplyr::select(SurveyID, Group, `Trial 1 TTH`, `Trial 2 TTH`, `trial 1 ebl`, `trial 2 ebl`) %>%
  gather(var, value, -SurveyID, -Group) %>%
  mutate(variable = gsub('.* ', '', var)) %>%
  mutate(trial = stringr::str_extract(string=var, pattern='[0-9]+')) %>%
  reshape2::dcast(SurveyID + Group + trial ~ variable, value.var='value')

change_in_scores <- scatter_ebl_tth %>% 
  setDT() %>% 
  dcast(SurveyID + Group ~ trial, value.var=c('ebl', 'TTH')) %>%
  mutate(change_in_tth=TTH_1 - TTH_2, change_in_ebl = ebl_1 - ebl_2)

ordered_survey_id <- change_in_scores %>%
  arrange(change_in_tth) %$%
  SurveyID

change_in_scores %<>% mutate(SurveyID = factor(SurveyID, levels=ordered_survey_id))
# change_in_scores %<>% mutate(MI=ifelse(SurveyID %in% most_improved_data$SurveyID, 'Training Rescue', NA))
```

```{r}
m <- ggplot(geyser, aes(x = duration, y = waiting)) + geom_point() + xlim(0.5, 6) + ylim(40, 110) 
m + geom_density2d()

dens <- kde2d(geyser$duration , geyser$waiting, n = 50, lims = c(0.5, 6, 40, 110)) 
densdf <- data.frame(expand.grid(duration = dens$x , waiting = dens$y), z = as.vector(dens$z))

m + geom_contour(aes(z=z), data=densdf)
m + geom_density2d() + scale_y_log10() 
m + geom_density2d() + coord_trans(y="log10")
m + stat_density2d(aes(fill = ..level..), geom="polygon")
```

```{r}
t1_dens_values <- scatter_ebl_tth %>% filter(trial == 1, !is.na(TTH), !is.na(ebl)) %$% kde2d(TTH, ebl)
t1_densdf <- data.frame(expand.grid(TTH=t1_dens_values$x , ebl=t1_dens_values$y), z=as.vector(t1_dens_values$z))

t2_dens_values <- scatter_ebl_tth %>% filter(trial == 2, !is.na(TTH), !is.na(ebl)) %$% kde2d(TTH, ebl)
t2_densdf <- data.frame(expand.grid(TTH=t2_dens_values$x , ebl=t2_dens_values$y), z=as.vector(t2_dens_values$z))

scale_max_to_use <- max(t1_densdf$z, t2_densdf$z)

plot_margin = 0.35

# TTH vs. EBL density heatmap
tth_ebl_heatmap_t1 <- ggplot(scatter_ebl_tth %>% filter(trial == 1), aes(TTH, ebl)) +
  stat_density_2d(aes(fill = ..density..), geom = "raster", contour = FALSE) +
  scale_fill_distiller(palette= "Spectral", direction=-1, breaks=c(0, 8.2e-06), labels=c('Low', 'High'), limits=c(0, 8.2e-06)) +
  # guides(fill=guide_legend()) +
  scale_x_continuous(expand = c(0, 0), limits=c(0, max(scatter_ebl_tth$TTH))) +
  scale_y_continuous(expand = c(0, 0), limits=c(0, max(scatter_ebl_tth$ebl))) +
  ggtitle('Trial 1 EBL vs. TTH density') +
  xlab('Time to Hemostatis (sec)') + ylab('Estimated Blood Loss (mL)') +
  facet_wrap(~Group, ncol=1) +
  theme(
    # axis.title = element_text(size = 12),
    axis.text = element_text(size=12),
    axis.title = element_blank(),
    # legend.position = 'none',
    strip.text = element_text(size=12),
    plot.margin=unit(c(plot_margin, plot_margin, plot_margin, plot_margin),"cm")
  )

# TTH vs. EBL density heatmap
tth_ebl_heatmap_t2 <- ggplot(scatter_ebl_tth %>% filter(trial == 2), aes(TTH, ebl)) +
  stat_density_2d(aes(fill = ..density..), geom = "raster", contour = FALSE) +
  scale_fill_distiller(palette= "Spectral", direction=-1) +
  scale_x_continuous(expand = c(0, 0), limits=c(0, max(scatter_ebl_tth$TTH)+30)) +
  scale_y_continuous(expand = c(0, 0), limits=c(0, max(scatter_ebl_tth$ebl))) +
  xlab('Time to Hemostatis (sec)') + ylab('Estimated Blood Loss (mL)') +
  ggtitle('Trial 2 EBL vs. TTH density') +
  facet_wrap(~Group, ncol=1) +
  theme(
    # axis.title = element_text(size = 12),
    axis.text = element_text(size=12),
    axis.title = element_blank(),
    legend.position = 'none',
    strip.text = element_text(size=12),
    plot.margin=unit(c(plot_margin, plot_margin, plot_margin, plot_margin),"cm")
  )
```

```{r}
figure_1_density <- annotate_figure(ggpubr::ggarrange(
  tth_ebl_heatmap_t1,
  tth_ebl_heatmap_t2, 
  ncol = 2, common.legend = TRUE, legend = 'right'
), left = text_grob("Estimated Blood Loss (mL)", size = 12, rot = 90), bottom = text_grob("Time to Hemostasis (sec)", size=12))

ggsave(figure_1_density, filename = file.path(plot_dir, 'figure_1_density.png'), width = 7 , height = 6, units = 'in')
```

```{r}
tth_columns <- raw_data %>% colnames() %>% .[grep('TTH', .)] %>% setdiff(., c('Trial 1 TTH_1', 'Trial 2 TTH_1'))
ebl_columns <- raw_data %>% colnames() %>% .[grep('ebl', .)]

most_improved_data <- raw_data %>%
  dplyr::select(SurveyID, Group, tth_columns, `Trial 1 Success`, `Trial 2 Success`) %>%
  gather(var, value, -SurveyID, -Group, -`Trial 1 Success`, -`Trial 2 Success`) %>%
  mutate(trial = gsub(' TTH', '', var)) %>%
  mutate(trial=factor(trial, c('Trial 1', 'Trial 2', 'Trial 3'))) %>%
  filter(`Trial 1 Success` == 0, `Trial 2 Success` == 1) %>%
  dplyr::rename(tth=value) %>%
  left_join(., 
    raw_data %>%
      dplyr::select(SurveyID, Group, `Trial 1 Success`, `Trial 2 Success`, ebl_columns) %>%
      magrittr::set_colnames(gsub('  ', ' ', colnames(.))) %>%
      gather(var, value, -SurveyID, -Group, -`Trial 1 Success`, -`Trial 2 Success`) %>%
      mutate(trial = gsub(' ebl', '', var)) %>%
      mutate(trial=factor(gsub('^t', 'T', trial), c('Trial 1', 'Trial 2', 'Trial 3'))) %>%
      filter(`Trial 1 Success` == 0, `Trial 2 Success` == 1) %>%
      dplyr::select(SurveyID, trial, ebl=value),
    by = c('SurveyID', 'trial')
  )
```

```{r}
change_in_scores <- raw_data %>% 
  dplyr::select(SurveyID, Group, `Trial 1 TTH`, `Trial 2 TTH`, `trial 1 ebl`, `trial 2 ebl`) %>%
  gather(var, value, -SurveyID, -Group) %>%
  mutate(variable = gsub('.* ', '', var)) %>%
  mutate(trial = stringr::str_extract(string=var, pattern='[0-9]+')) %>%
  reshape2::dcast(SurveyID + Group + trial ~ variable, value.var='value') %>% 
  setDT() %>% 
  dcast(SurveyID + Group ~ trial, value.var=c('ebl', 'TTH')) %>%
  mutate(change_in_tth=TTH_1 - TTH_2, change_in_ebl = ebl_1 - ebl_2)

ordered_survey_id <- change_in_scores %>%
  arrange(change_in_tth) %$%
  SurveyID

change_in_scores %<>% mutate(SurveyID = factor(SurveyID, levels=ordered_survey_id))
change_in_scores %<>% mutate(Group2=ifelse(SurveyID %in% most_improved_data$SurveyID, 'Training rescue', 'Other'))
```

```{r}
quartile_cutoff <- change_in_scores %$% quantile(change_in_tth, na.rm=T, c(0.75))
change_in_scores %<>% mutate(Group3=ifelse(change_in_tth >= quartile_cutoff, 'MIQ', 'Other'))
```

```{r}
jama_colors <- pal_jama("default")(7)
trial_1_rank_order <- change_in_scores %>% arrange(TTH_1, -change_in_tth) %$% SurveyID
absolute_change_in_tth <- ggplot(change_in_scores %>% mutate(SurveyID=factor(SurveyID, levels=trial_1_rank_order)), aes(color=Group2)) +
  geom_segment(aes(x = SurveyID, xend=SurveyID, y = TTH_1, yend = TTH_2)) +
  geom_point(aes(x=SurveyID, y= TTH_1), color = jama_colors[1], alpha=0.75) +
  geom_point(aes(x=SurveyID, y= TTH_2), color=jama_colors[2], alpha=0.75) +
  guides(color=guide_legend(title=NULL)) +
  # scale_linetype_manual(values = c('Training rescue'=1), na.value = 2) +
  scale_color_manual(values=c('Training rescue'='black', 'MIQ'='black', 'Other'='grey'), breaks=c('Training rescue', 'Other'),na.value='grey') +
  xlab('Individual ranked by improvement in TTH') +
  ylab('Time to Hemostasis (sec)') +
  theme_bw() +
  theme(
    legend.position = 'top',
    legend.justification = 'left',
    legend.text = element_text(size=12),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size=12),
    axis.title = element_text(size=12),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank()
  )

absolute_change_in_tth
```


```{r}
quartile_cutoff <- change_in_scores %$% quantile(change_in_tth, na.rm=T, c(0.75))
data_top_quartile <- change_in_scores %>% 
  filter(change_in_tth >= quartile_cutoff)

attending_stats_years_in_training_quantile <- raw_data %>%
  filter(SurveyID %in% data_top_quartile$SurveyID, Group == 'Attending') %>%
  dplyr::select(Attyears)

top_quartile_mean_values <- data_top_quartile %>%
  summarise_if(is.numeric, median) %>%
  mutate(tth_improvement=(1-TTH_2/TTH_1)*100, ebl_improvement=(1-ebl_2/ebl_1)*100)

tth_top_quartile_stats <- data_top_quartile %$%
  t.test(TTH_1, TTH_2, paired = TRUE)

ebl_top_quartile_stats <- data_top_quartile %$%
  t.test(ebl_1, ebl_2, paired = TRUE)

quartile_success_rates <- preprocess_for_success_rate %>%
  filter(SurveyID %in% data_top_quartile$SurveyID) %>%
  group_by(trial) %>%
  dplyr::summarise(
    perc_success=sum(s)/n()*100
  )

quartile_success_stat_prep <- preprocess_for_success_rate %>%
  filter(SurveyID %in% data_top_quartile$SurveyID) %>%
  group_by(trial, s) %>%
  dplyr::summarise(count=n()) %>%
  dcast(s ~ trial, value.var='count')

quartile_success_stat_prep[is.na(quartile_success_stat_prep)] <- 0
quartile_success_stat <- fisher.test(quartile_success_stat_prep[,c('Trial 1', 'Trial 2')])
```

```{r}
quartiles_all_miq <- change_in_scores %$% quantile(change_in_ebl, na.rm=T, c(0.25, 0.5, 0.75, 1.00))

change_in_scores %<>%
  mutate(quart=case_when(
    change_in_ebl <= quartiles_all_miq[1] ~ 'Q4\nLeast\nImproved',
    change_in_ebl <= quartiles_all_miq[2] ~ 'Q3',
    change_in_ebl <= quartiles_all_miq[3] ~ 'Q2',
    change_in_ebl <= quartiles_all_miq[4] ~ 'Q1\nMost\nImproved',
    TRUE ~ 'None'
  ))

quartiles_plotting <- change_in_scores %>%
  dplyr::select(SurveyID, Group, quart, ebl_1, ebl_2, change_in_ebl) %>%
  gather(var, val, -SurveyID, -Group, -quart, -change_in_ebl) %>%
  mutate(var=gsub('TTH_', 'Trial', var)) %>%
  mutate(var=gsub('ebl_', 'Trial ', var))

miq_box_plot <- ggplot(quartiles_plotting %>% filter(quart != 'None'), aes(quart, val, color=var)) +
  # geom_boxplot(alpha=0.5, outlier.shape = NA) +
  guides(color=guide_legend(title=NULL)) +
  scale_color_jama() +
  scale_fill_jama() +
  geom_point(position = position_jitterdodge(dodge.width = 0.75, jitter.width = 0.2), size=2, alpha=0.75) +
  # stat_summary(position = position_dodge(width = 0.75), aes(group=var), fun.y = median, fun.ymin = median, fun.ymax = median, geom = "crossbar", width = 0.25, color='black') +
  xlab('Improvement Quartile') + ylab('Estimated Blood Loss (mL)') +
  theme_bw() +
  theme(
    legend.position = 'top',
    legend.justification = 'left',
    axis.text = element_text(size=12),
    legend.text = element_text(size=12),
    axis.title = element_text(size=12)
  )

miq_box_plot
```

```{r}
figure1_miq_performance <- ggpubr::ggarrange(
  absolute_change_in_tth, miq_box_plot, labels = c('b', 'c'), nrow = 1
)

ggsave(figure1_miq_performance, filename = file.path(plot_dir, 'figure1_miq_performance.png'), width = 8, height = 4, units = 'in')
```

```{r}
# Final figure 1
final_figure1 <- ggpubr::ggarrange(
  figure_1_density, 
  figure1_miq_performance, labels = c('a', ''),
  nrow = 2, ncol = 1, heights = c(1.5, 1))

ggsave(final_figure1, filename = file.path(final_figure_dir, 'figure1.png'), width = 8, height = 10, units='in')
```







