---
title: "Figure 4"
author: "Guillaume Kugener"
date: "5/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pROC)
library(plotROC)
source('~/Documents/USC/USC_docs/ml/surgical-training-project/analysis/carotid_model/preprocess_data.R')
```

```{r}
confidence_value_order <- c(
  'Training level'='GroupTrainee',
  'General\n confidence\npre-trial'='generalconfidencepre', 'General\nconfidence\npost-trial'='generalconfidencepost', 
  'Carotid\nconfidence\npre-trial'='carotidconfidencepre', 'Carotid\nconfidence\npost-trial'='carotidconfidencepost', 
  'Specialty'='SpecialtyOtolaryngology',
  'Prior\nreal ICA'='priorreal', 'Prior\nsimulation'='priorsim',
  'Total years\nin training'='Totyears', 'Years as\nattending'='Attyears', 
  'Endoscopic\nlast 12\nmonths'='endolast12mo', 'Cadaver\nlast 12\nmonths'='cadaverlast12'
)

# logistic regression - what predicts trial 1 success from a set of variables that we have
pred_logisit_data <- raw_data %>%
  dplyr::select(
    SurveyID, Group, Source,
    `Trial 1 Success`, `Trial 2 Success`,
    `Trial 1 TTH`, `Trial 2 TTH`, `trial 1 ebl`, `trial 2 ebl`,
    generalconfidencepre, generalconfidencepost,
    carotidconfidencepre, carotidconfidencepost,
    priorreal, priorsim,
    Attyears, endolast12mo, cadaverlast12
  ) %>% mutate(Group=factor(Group)) %>%
  mutate(Attyears=ifelse(Group=='Trainee', 0, Attyears))
```

## Demos vs. performance (success, TTH, EBL)

```{r}
demographics_pred_logisit_data <- raw_data %>%
  dplyr::select(
    SurveyID, Group, Source,
    `Trial 1 Success`, `Trial 2 Success`,
    `Trial 1 TTH`, `Trial 2 TTH`, `trial 1 ebl`, `trial 2 ebl`,
    Specialty,
    priorreal, priorsim,
    Totyears, Attyears, endolast12mo, cadaverlast12,
    generalconfidencepre, carotidconfidencepre, carotidconfidencepost, generalconfidencepost
  ) %>% mutate(Group=factor(Group)) %>%
  mutate(Attyears=ifelse(Group=='Trainee', 0, Attyears))
```

```{r}
dems_t1s_pred <- glm(`Trial 1 Success` ~ Attyears + Specialty + priorsim + priorreal + endolast12mo + cadaverlast12 + generalconfidencepre + carotidconfidencepre, data=demographics_pred_logisit_data, family = 'binomial')
dems_t2s_pred <- glm(`Trial 2 Success` ~ Attyears + Specialty + priorsim + priorreal + endolast12mo + cadaverlast12 + generalconfidencepre + carotidconfidencepre, data=demographics_pred_logisit_data, family = 'binomial')

nrow(demographics_pred_logisit_data) - (summary(dems_t1s_pred)$na.action %>% length())
nrow(demographics_pred_logisit_data) - (summary(dems_t2s_pred)$na.action %>% length())

# Train logistic regression
dems_results_logit_data <- data.frame(
  coeff_names=names(coefficients(dems_t1s_pred)),
  T1_c=coefficients(dems_t1s_pred),
  T1_p=coef(summary(dems_t1s_pred))[,4],
  T2_c=coefficients(dems_t2s_pred),
  T2_p=coef(summary(dems_t2s_pred))[,4],
  stringsAsFactors = F
) %>%
  gather(var, value, -coeff_names) %>%
  mutate(
    trial = stringr::str_extract(string=var, pattern='^T[12]'),
    variable = stringr::str_extract(string=var, pattern='[cp]$')
  ) %>% reshape2::dcast(coeff_names + trial ~ variable, value.var='value') %>%
  filter(coeff_names != '(Intercept)') %>%
  mutate(coeff_names=factor(coeff_names, levels=c(confidence_value_order))) %>%
  mutate(trial=gsub('^T', 'Trial ', trial))
```

```{r}
# ANOVA success
anova_t1s_pred <- aov(`Trial 1 Success` ~ generalconfidencepre + generalconfidencepost + carotidconfidencepre + carotidconfidencepost, data=pred_logisit_data)
summary(anova_t1s_pred)

anova_t2s_pred <- aov(`Trial 2 Success` ~ generalconfidencepre + generalconfidencepost + carotidconfidencepre + carotidconfidencepost, data=pred_logisit_data)
summary(anova_t2s_pred)

```

```{r}
# Confidence + group predictions
t1s_pred <- glm(`Trial 1 Success` ~ generalconfidencepre + generalconfidencepost + carotidconfidencepre + carotidconfidencepost, data=pred_logisit_data, family = 'binomial')
t2s_pred <- glm(`Trial 2 Success` ~ generalconfidencepre + generalconfidencepost + carotidconfidencepre + carotidconfidencepost, data=pred_logisit_data, family = 'binomial')

nrow(pred_logisit_data) - (summary(t1s_pred)$na.action %>% length())
nrow(pred_logisit_data) - (summary(t2s_pred)$na.action %>% length())

# Train logistic regression
results_logit_data <- data.frame(
  coeff_names=names(coefficients(t1s_pred)),
  T1_c=coefficients(t1s_pred),
  T1_p=coef(summary(t1s_pred))[,4],
  T2_c=coefficients(t2s_pred),
  T2_p=coef(summary(t2s_pred))[,4],
  stringsAsFactors = F
) %>%
  gather(var, value, -coeff_names) %>%
  mutate(
    trial = stringr::str_extract(string=var, pattern='^T[12]'),
    variable = stringr::str_extract(string=var, pattern='[cp]$')
  ) %>% reshape2::dcast(coeff_names + trial ~ variable, value.var='value') %>%
  filter(coeff_names != '(Intercept)') %>%
  mutate(coeff_names=factor(coeff_names, levels=c(confidence_value_order))) %>%
  mutate(trial=gsub('^T', 'Trial ', trial))
```

```{r eval=FALSE}
demographics_pred_logisit_data$t1_pred <- predict(dems_t1s_pred,newdata = demographics_pred_logisit_data)
demographics_pred_logisit_data$t2_pred <- predict(dems_t2s_pred,newdata = demographics_pred_logisit_data)

ggplot() +
  geom_roc(data = demographics_pred_logisit_data %>% 
      filter(!is.na(`Trial 1 Success`)), 
    aes(m = t1_pred, d = `Trial 1 Success`), 
    n.cuts=20, labels=F, color=jama_colors[1]) +
  geom_roc(data = demographics_pred_logisit_data %>% 
      filter(!is.na(`Trial 2 Success`)), 
    aes(m = t2_pred, d = `Trial 1 Success`), 
    n.cuts=20, labels=F, color=jama_colors[2]) +
  geom_abline(slope=1, linetype=2)
```

```{r}
max_variable_value_across_logits_trials <- max(abs(dems_results_logit_data$c), abs(results_logit_data$c))
```


```{r}
breaks_dems_trial_success_conf_multi <- confidence_value_order[which(confidence_value_order %in% dems_results_logit_data$coeff_names)]

dems_trial_success_conf_multi <- ggplot(dems_results_logit_data, aes(coeff_names, abs(c), fill=trial)) +
  geom_bar(stat='identity', position=position_dodge()) + 
  geom_text(data = dems_results_logit_data %>%
      mutate(text=ifelse(p < 0.05, paste0('p=', round(p, 2)), 'ns'), y=max(abs(max_variable_value_across_logits_trials))*1.1),
    aes(coeff_names, y, label=text, color=trial), size=12/ggplot2:::.pt, position = position_dodge(width=1), vjust=1) +
  guides(fill=guide_legend(title=NULL), color=FALSE) +
  scale_fill_jama() +
  scale_color_jama() +
  xlab('Variable') + ylab('Trial success model weight') +
  scale_x_discrete(breaks=breaks_dems_trial_success_conf_multi, labels=names(breaks_dems_trial_success_conf_multi)) +
  scale_y_continuous(expand=c(0, 0)) +
  # ggtitle('Multivariate prediction of trial success') +
  theme_bw() +
  theme(
    legend.position = 'top',
    legend.justification = 'left',
    legend.text = element_text(size=12),
    axis.text = element_text(size=12),
    axis.text.x = element_text(size=10),
    axis.title = element_text(size=12),
    axis.title.x = element_blank()
  )

dems_trial_success_conf_multi
```


```{r}
conf_breaks_trial_sucess_conf_multi <- confidence_value_order[which(confidence_value_order %in% results_logit_data$coeff_names)]
trial_success_conf_multi <- ggplot(results_logit_data, aes(coeff_names, abs(c), fill=trial)) +
  geom_bar(stat='identity', position=position_dodge()) + 
  geom_text(data = results_logit_data %>%
      mutate(text=ifelse(p < 0.05, paste0('p=', round(p, 2)), 'ns'), y=max(max_variable_value_across_logits_trials)*1.1),
    aes(coeff_names, y, label=text, color=trial), size=12/ggplot2:::.pt, position = position_dodge(width=1), vjust=1) +
  guides(fill=guide_legend(title=NULL), color=FALSE) +
  scale_fill_jama() +
  scale_color_jama() +
  # ggtitle('Multivariate prediction of trial success') +
  guides(fill=guide_legend(title=NULL)) +
  xlab('Variable') + ylab('Trial success model weight') +
  scale_x_discrete(breaks=conf_breaks_trial_sucess_conf_multi, labels=names(conf_breaks_trial_sucess_conf_multi)) +       
  scale_y_continuous(expand=c(0, 0)) +
  # ggtitle('Multivariate prediction of trial success') +
  theme_bw() +
  theme(
    legend.position = 'none',
    legend.justification = 'left',
    legend.text = element_text(size=12),
    axis.text = element_text(size=12),
    axis.text.x = element_text(size=10),
    axis.title = element_text(size=12),
    axis.title.x = element_blank()
  )

trial_success_conf_multi
```

```{r}
tth_t1s_pred <- lm(`Trial 1 TTH` ~ generalconfidencepre + generalconfidencepost + carotidconfidencepre + carotidconfidencepost, data=pred_logisit_data)
tth_t2s_pred <- lm(`Trial 2 TTH` ~ generalconfidencepre + generalconfidencepost + carotidconfidencepre + carotidconfidencepost, data=pred_logisit_data)

# Train logistic regression
tth_results_lm_data <- data.frame(
  coeff_names=names(coefficients(tth_t1s_pred)),
  T1_c=coefficients(tth_t1s_pred),
  T1_p=coef(summary(tth_t1s_pred))[,4],
  T2_c=coefficients(tth_t2s_pred),
  T2_p=coef(summary(tth_t2s_pred))[,4],
  stringsAsFactors = F
) %>%
  gather(var, value, -coeff_names) %>%
  mutate(
    trial = stringr::str_extract(string=var, pattern='^T[12]'),
    variable = stringr::str_extract(string=var, pattern='[cp]$')
  ) %>% reshape2::dcast(coeff_names + trial ~ variable, value.var='value') %>%
  filter(coeff_names != '(Intercept)') %>%
  mutate(coeff_names=factor(coeff_names, levels=c(confidence_value_order))) %>%
  mutate(trial=gsub('^T', 'Trial ', trial))

tth_success_conf_multi <- ggplot(tth_results_lm_data, aes(coeff_names, abs(c), fill=trial)) +
  geom_bar(stat='identity', position=position_dodge()) + 
  geom_text(data = tth_results_lm_data %>%
      mutate(text=ifelse(p < 0.05, paste0('p=', round(p, 2)), 'ns'), y=max(abs(tth_results_lm_data$c))*1.1),
    aes(coeff_names, y, label=text, color=trial), size=12/ggplot2:::.pt, position = position_dodge(width=1), vjust=1) +
  guides(fill=guide_legend(title=NULL), color=FALSE) +
  scale_fill_jama() +
  scale_color_jama() +
  # ggtitle('Multivariate prediction of TTH') +
  guides(fill=guide_legend(title=NULL)) +
    xlab('Variable') + ylab('TTH Model weight') +
  scale_x_discrete(breaks=conf_breaks_trial_sucess_conf_multi, labels=names(conf_breaks_trial_sucess_conf_multi)) +
  scale_y_continuous(expand=c(0, 0)) +
  # ggtitle('Multivariate prediction of trial success') +
  theme_bw() +
  theme(
    legend.position = 'none',
    # legend.justification = 'left',
    legend.text = element_text(size=12),
    axis.text = element_text(size=12),
    axis.text.x = element_text(size=10),
    axis.title = element_text(size=12),
    axis.title.x = element_blank()
  )
tth_success_conf_multi
```

```{r}
plotting_data_ebl_conf <- pred_logisit_data %>%
  dplyr::select(SurveyID, Group, `trial 1 ebl`, `trial 2 ebl`, carotidconfidencepre, carotidconfidencepost) %>%
  gather(conf, conf_val, -SurveyID, -Group, -`trial 1 ebl`, -`trial 2 ebl`) %>%
  gather(trial, ebl, -SurveyID, -Group, -conf, -conf_val) %>%
  filter(!is.na(conf_val)) %>%
  filter((grepl('pre', conf) & grepl('1', trial)) | (grepl('post', conf) & grepl('2', trial))) %>%
  mutate(conf_val=factor(conf_val)) %>%
  mutate(trial=ifelse(trial == 'trial 1 ebl', 'Trial 1', 'Trial 2'))

failed_trial_1 <- pred_logisit_data %>% filter(`Trial 1 Success` == 0) %$% SurveyID
failed_trial_2 <- pred_logisit_data %>% filter(`Trial 2 Success` == 0) %$% SurveyID

plotting_data_ebl_conf <- plotting_data_ebl_conf %>%
  mutate(failed=ifelse(
    (SurveyID %in% failed_trial_1 & grepl('pre', conf)) | (SurveyID %in% failed_trial_2 & grepl('post', conf)), 'Fail', 'Success'))

# Will make two plots so that the axis are consistent
sample_2 <- ggplot(plotting_data_ebl_conf, aes(conf_val, ebl, color=failed)) +
  # geom_boxplot(color='black', alpha=0.5, fill='grey', outlier.shape = NA) +
  geom_point(position = position_jitter(width=0.2), size=2, alpha=0.5) +
  # geom_sina() +
  # geom_smooth(method = 'lm') +
  stat_summary(fun.y = median, fun.ymin = median, fun.ymax = median, geom = "crossbar", width = 0.25, color='black') +
  # stat_summary(fun.data=mean_se, geom = 'errorbar', color='black',width=0.2) +
  facet_wrap(~trial) +
  guides(color=guide_legend(title=NULL)) +
  # scale_fill_jama() +
  # scale_color_jama() +
  # ggtitle('Multivariate prediction of TTH') +
  guides(fill=guide_legend(title=NULL, override.aes = list(alpha=1))) +
  xlab('Carotid Confidence') + ylab('Estimated Blood Loss (mL)') +
  # ggtitle('Multivariate prediction of trial success') +
  theme_bw() +
  # facet_wrap() +
  theme(
    legend.position = 'top',
    legend.justification = 'left',
    legend.text = element_text(size=12),
    axis.text = element_text(size=12),
    axis.title = element_text(size=12)
  )

sample_2

# ggsave(sample_2, filename = '~/Downloads/plot2.png', width = 8, height = 5)
```

```{r}
ebl_t1s_pred <- lm(`trial 1 ebl` ~ generalconfidencepre + generalconfidencepost + carotidconfidencepre + carotidconfidencepost, data=pred_logisit_data)
ebl_t2s_pred <- lm(`trial 2 ebl` ~ generalconfidencepre + generalconfidencepost + carotidconfidencepre + carotidconfidencepost, data=pred_logisit_data)

# Train logistic regression
ebl_results_lm_data <- data.frame(
  coeff_names=names(coefficients(tth_t1s_pred)),
  T1_c=coefficients(ebl_t1s_pred),
  T1_p=coef(summary(ebl_t1s_pred))[,4],
  T2_c=coefficients(ebl_t2s_pred),
  T2_p=coef(summary(ebl_t2s_pred))[,4],
  stringsAsFactors = F
) %>%
  gather(var, value, -coeff_names) %>%
  mutate(
    trial = stringr::str_extract(string=var, pattern='^T[12]'),
    variable = stringr::str_extract(string=var, pattern='[cp]$')
  ) %>% reshape2::dcast(coeff_names + trial ~ variable, value.var='value') %>%
  filter(coeff_names != '(Intercept)') %>%
  mutate(coeff_names=factor(coeff_names, levels=c(confidence_value_order))) %>%
  mutate(trial=gsub('^T', 'Trial ', trial))

ebl_success_conf_multi <- ggplot(ebl_results_lm_data, aes(coeff_names, abs(c), fill=trial)) +
  geom_bar(stat='identity', position=position_dodge()) + 
  geom_text(data = ebl_results_lm_data %>%
      mutate(text=ifelse(p < 0.05, paste0('p=', round(p, 2)), 'ns'), y=max(abs(ebl_results_lm_data$c))*1.1),
    aes(coeff_names, y, label=text, color=trial), size=12/ggplot2:::.pt, position = position_dodge(width=1), vjust=1) +
  guides(fill=guide_legend(title=NULL), color=FALSE) +
  scale_fill_jama() +
  scale_color_jama() +
  # ggtitle('Multivariate prediction of TTH') +
  guides(fill=guide_legend(title=NULL)) +
    xlab('Variable') + ylab('EBL Model weight') +
  scale_x_discrete(breaks=conf_breaks_trial_sucess_conf_multi, labels=names(conf_breaks_trial_sucess_conf_multi)) +
  scale_y_continuous(expand=c(0, 0)) +
  # ggtitle('Multivariate prediction of trial success') +
  theme_bw() +
  theme(
    legend.position = 'none',
    # legend.justification = 'left',
    legend.text = element_text(size=12),
    axis.text = element_text(size=12),
    axis.text.x = element_text(size=10),
    axis.title = element_text(size=12),
    axis.title.x = element_blank()
  )
ebl_success_conf_multi
```

```{r include=FALSE}
heart_rate_columns <- raw_data %>% colnames() %>% .[grep('Peak|Average', .)]
heart_rate_data <- raw_data %>%
  dplyr::select(SurveyID, Group, heart_rate_columns) %>%
  gather(var, value, -SurveyID, -Group) %>%
  mutate(
    timing=stringr::str_extract(pattern='Base?line|Trial [12]|Intertrial|Posttrial', var),
    value_type = stringr::str_extract(pattern='Peak|Average', var)
  ) %>%
  mutate(timing=gsub('Basline', 'Baseline', timing)) %>%
  mutate(timing=factor(timing, c('Baseline', 'Trial 1', 'Intertrial', 'Trial 2', 'Posttrial')))

# To look for those that have complete data
counts_by_individual <- heart_rate_data %>%
  filter(value_type=='Peak') %>%
  group_by(SurveyID) %>%
  dplyr::summarise(count=length(which(!is.na(value)))) %>%
  arrange(-count)

complete_heart_rate_data <- heart_rate_data %>%
  filter(SurveyID %in% (counts_by_individual %>% filter(count > 2) %$% SurveyID))

clean_heart_rate_data <- complete_heart_rate_data %>%
  dcast(SurveyID + Group + value_type ~ timing, value.var='value') %>%
  filter(!is.na(Baseline), !is.na(`Trial 1`)) %>%
  mutate(
    PT1=`Trial 1`/Baseline, 
    PIT=Intertrial/Baseline, 
    PT2=`Trial 2`/Baseline, 
    PPT=Posttrial/Baseline
  )
```

```{r}
base_line_t1_peak_avg <- clean_heart_rate_data %>%
  filter(value_type=='Average') %$%
  t.test(`Trial 1`, Baseline, paired = T)

base_line_t2_peak_avg <- clean_heart_rate_data %>%
  filter(value_type=='Average') %$%
  t.test(`Trial 2`, Baseline, paired = T)

number_tachycardic <- complete_heart_rate_data %>%
  group_by(value_type, timing) %>%
  dplyr::summarise(
    num_tachy=length(value[value > 100]), 
    percent_tachy=length(value[value > 100])/n(),
    num_extreme_tachy=length(value[value > 120]), 
    percent_extreme_tachy=length(value[value > 120])/n(),
    total=n()
  )

contig_table_values <- number_tachycardic %>%
  filter(timing %in% c('Baseline', 'Trial 1', 'Intertrial', 'Trial 2', 'Posttrial')) %>%
  mutate(num_not_tachy=total-num_tachy, num_not_e_tachy=total-num_extreme_tachy) %>%
  dplyr::select(value_type, timing, num_tachy, num_not_tachy, num_extreme_tachy, num_not_e_tachy)

tachy_table <- contig_table_values %>%
  ungroup() %>%
  filter(value_type=='Peak', timing %in% c('Baseline', 'Trial 1')) %>%
  dplyr::select(timing, num_tachy, num_not_tachy) %>%
  column_to_rownames('timing') %>%
  fisher.test()

extreme_tachy_table <- contig_table_values %>%
  ungroup() %>%
  filter(value_type=='Peak', timing %in% c('Baseline', 'Trial 1')) %>%
  dplyr::select(timing, num_extreme_tachy, num_not_e_tachy) %>%
  column_to_rownames('timing') %>%
  fisher.test()

significance_hr <- NULL
for (i in c('Trial 1', 'Intertrial', 'Trial 2', 'Posttrial')) {
  for (j in c('Average', 'Peak')) {
    for (k in c('Baseline', 'Intertrial')) {
      da <- clean_heart_rate_data %>%
        filter(value_type==j)
      p_val <- t.test(da[,i], da[,k])$p.value
      
      significance_hr %<>% rbind(data.frame(base=k, timing=i, value_type=j, p=p_val)) 
    }
  }
}

significance_hr %<>% 
  mutate(timing=factor(timing, levels=c('Baseline', 'Trial 1', 'Intertrial', 'Trial 2', 'Posttrial'))) %>%
  mutate(label=ifelse(p < 0.05, '*', 'ns'))
```

```{r}
# Simple box plot of heart rate data
heart_rate_data_bar <- complete_heart_rate_data %>%
  group_by(timing, value_type) %>%
  dplyr::summarise(m=mean(value, na.rm = T), s=sd(value, na.rm = T)/sqrt(length(value[!is.na(value)]))) %>%
  ungroup() %>%
  mutate(timing=factor(timing, levels=c('Baseline', 'Trial 1', 'Intertrial', 'Trial 2', 'Posttrial')))
```

```{r}
heart_comparisons <- list( c("Baseline", "Trial 1"), c("Baseline", "Intertrial"), c("Intertrial", "Trial 2"), c("Trial 1", "Trial 2"))
jama_colors <- pal_jama("default")(7)

average_heart_rate_plot <- ggplot(complete_heart_rate_data %>% filter(value_type=='Average'), aes(timing, value, color=timing, fill=timing)) +
  # geom_boxplot(outlier.shape = NA) +
  stat_summary(fun.y = mean, geom = 'bar', na.rm = T, color='black', alpha=0.5) +
  stat_summary(fun.data=mean_se, geom = 'errorbar', color='black',width=0.2) +
  # geom_sina(alpha=0.5) +
  geom_path(data=heart_rate_data_bar %>% filter(value_type == 'Average'), aes(timing, m, group=value_type), size=1.5, color='black') +
  stat_compare_means(comparisons = heart_comparisons, 
    method = 't.test', paired = T, label = 'p.format', 
    label.y = c(110, 113, 119, 116), tip.length = 0.005) +
  scale_color_manual(values=c('Baseline'='grey', 'Trial 1'=jama_colors[1], 'Intertrial'='grey', 'Trial 2'=jama_colors[2], 'Posttrial'='grey')) +
  scale_fill_manual(values=c('Baseline'='grey', 'Trial 1'=jama_colors[1], 'Intertrial'='grey', 'Trial 2'=jama_colors[2], 'Posttrial'='grey')) +
  ylab('Average heart rate (beats/min)') +
  coord_cartesian(ylim = c(85, 120)) +
  theme_bw() +
  theme(
    legend.position = 'none',
    axis.text = element_text(size=12),
    axis.title = element_text(size=12),
    axis.title.x = element_blank()
  )

peak_heart_rate_plot <- ggplot(complete_heart_rate_data %>% filter(value_type=='Peak'), aes(timing, value, color=timing, fill=timing)) +
  # geom_boxplot(outlier.shape = NA) +
  stat_summary(fun.y = mean, geom = 'bar', na.rm = T, color='black', alpha=0.5) +
  stat_summary(fun.data=mean_se, geom = 'errorbar', color='black',width=0.2) +
  # geom_sina(alpha=0.5) +
  geom_path(data=heart_rate_data_bar %>% filter(value_type == 'Peak'), aes(timing, m, group=value_type), size=1.5, color='black') +
  stat_compare_means(comparisons = heart_comparisons, 
    method = 't.test', paired = T, label = 'p.format', 
    label.y = c(110, 113, 119, 116), tip.length = 0.005) +
  scale_color_manual(values=c('Baseline'='grey', 'Trial 1'=jama_colors[1], 'Intertrial'='grey', 'Trial 2'=jama_colors[2], 'Posttrial'='grey')) +
  scale_fill_manual(values=c('Baseline'='grey', 'Trial 1'=jama_colors[1], 'Intertrial'='grey', 'Trial 2'=jama_colors[2], 'Posttrial'='grey')) +
  ylab('Peak heart rate (beats/min)') +
  coord_cartesian(ylim = c(85, 120)) +
  theme_bw() +
  theme(
    legend.position = 'none',
    axis.text = element_text(size=12),
    axis.title = element_text(size=12),
    axis.title.x = element_blank()
  )
```

```{r}
figure4 <- ggpubr::ggarrange(
  dems_trial_success_conf_multi,
  ggpubr::ggarrange(
    trial_success_conf_multi, tth_success_conf_multi, ncol=2, labels = c('b', 'c')
  ),
  ggpubr::ggarrange(
    average_heart_rate_plot, peak_heart_rate_plot, ncol=2, labels = c('d', 'e')
  ), nrow = 3, labels = c('a', '', '')
)

ggsave(figure4, filename = file.path(source_dir, 'figures', 'figure4.png'), width = 8, height = 10, units = 'in')
```

