---
title: "Redding out analysis"
author: "Guillaume Kugener"
date: "12/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(pROC)
```

We are interested in automating the labelling of endoscopic red out (when the visual field is almost completely covered by blood). RJP and GGK independently annotated ranges of red out in 10,000 frames of video. 


TODO: look at the concordance between graders when frames are at least 5 seconds, 10 seconds, 

Think about a red out threshold predictor

```{r}
redding_out <- read_tsv('~/Documents/USC/USC_docs/ml/surgical-training-project/file-preprocessing/output-test/redout-test.tsv') %>%
  mutate(index=rank(frame))
```

```{r}
ggplot(redding_out, aes(index, channel_2, color=redded_out)) + 
  geom_point(size=0.5) +
  # scale_color_manual(c('blue', 'red')) +
  xlim(7200, 7555) + 
  theme_bw()
```

```{r}
ggk_red_out <- read_tsv('~/Downloads/Red-Out - GGK Frames.tsv') %>%
  mutate(source='GGK')
djp_red_out <- read_tsv('~/Downloads/Red-Out - DJP Frames.tsv') %>%
  mutate(Notes=NA, source='DJP')

levels_order <- c('GGK', 'DJP')
red_outs_combined <- rbind(ggk_red_out, djp_red_out) %>%
  mutate(source=factor(source, levels=levels_order)) %>%
  mutate(y=as.integer(source))

redding_out_overall <- ggplot(red_outs_combined) +
  geom_rect(aes(xmin=`Start Frame`, xmax=`End Frame`, ymin=y-0.5, ymax=y+0.5), fill='red') +
  scale_y_continuous(expand = c(0,0), breaks=seq(1, length(levels_order)), labels=levels_order) +
  xlab('Frame') + ylab('Annotator') +
  theme_bw()
```

```{r}
redding_out_overall
```

```{r}
## Look at the agreement quantitatively
red_frames_ggk <- apply(ggk_red_out, 1, function(x) {
  seq(x[['Start Frame']], x[['End Frame']])
})

red_frames_ggk_all <- c()
for (rr in red_frames_ggk) {
  red_frames_ggk_all <- c(red_frames_ggk_all, rr)
}

red_frames_djp <- apply(djp_red_out, 1, function(x) {
  seq(x[['Start Frame']], x[['End Frame']])
})

red_frames_djp_all <- c()
for (rr in red_frames_djp) {
  red_frames_djp_all <- c(red_frames_djp_all, rr)
}

length(red_frames_djp_all)
length(red_frames_ggk_all)

overlapping_red_out <- intersect(red_frames_djp_all, red_frames_ggk_all)
overlapping_white_out <- intersect(
  setdiff(seq(1,10000), red_frames_djp_all),
  setdiff(seq(1,10000), red_frames_ggk_all)
)

```


```{r}
# Load metrics
generated_metrics_testing <- read_tsv('~/Documents/USC/USC_docs/ml/surgical-training-project/file-preprocessing/output-test/redout-testing-notebook.tsv')

generated_metrics_testing %<>%
  mutate(index=gsub('frame_0+', '', gsub('\\.jpeg', '', frame))) %>%
  mutate(GGK=ifelse(index %in% red_frames_ggk_all, 1, 0)) %>%
  mutate(RJP=ifelse(index %in% red_frames_djp_all, 1, 0))


generated_metrics_testing %>%
  filter(GGK != RJP) %>%
  dplyr::select(frame, GGK, RJP, everything())
```

```{r}
# head(generated_metrics_testing)
red_out_logit <- glm(GGK ~ channel_0 + channel_1 + channel_2, data = generated_metrics_testing, family = "binomial")

generated_metrics_testing$pred <- predict(red_out_logit, newdata = generated_metrics_testing)

g <- roc(GGK ~ pred, data = generated_metrics_testing)
# generated_metrics_testing %>%
#   filter(GGK == 1)

g
```

```{r}
colnames(generated_metrics_testing)

# head(generated_metrics_testing)
red_out_logit <- glm(GGK ~ ., 
  data = generated_metrics_testing %>%
    dplyr::select(-frame, -channel_0, -channel_1, -channel_2, -index, -RJP, -pred), family = "binomial")

summary(red_out_logit)

generated_metrics_testing$pred <- predict(red_out_logit, newdata = generated_metrics_testing)

g <- roc(GGK ~ pred, data = generated_metrics_testing)
# generated_metrics_testing %>%
#   filter(GGK == 1)

g
```



